### PR TITLE
chore: small update of the apply command help

### PR DESCRIPTION
**Pull request by astraios**

### CODE REVIEW

**Comment by b4nst** [comment]
I wonder if it's worth keeping this character. That was dumb of me. Maybe we can replace it with another one (`.`?)

**Comment by astraios** [comment]
Makes sense, I'll try and check in a new branch

**Comment by astraios** [comment]
Decide to stop using `$` to detect the user wants to extract the k8s config context from property set in the release's cue files. Closing

**Comment by b4nst** [comment]
In favor of  #43

**Pull request closed without merging**
